#:schema node_modules/wrangler/config-schema.json
name = "wood-consulting"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NPM_FLAGS = "--legacy-peer-deps"
# Add your environment variables here
